// @generated-scaffold — contract scaffold from the API catalogue; handlers answer 501 until built.
// Once you implement a handler, delete the first line so regeneration can never overwrite your work.
// The section order of the Swagger UI, persona by persona. Edit design/api-spec/spec/tags.mjs, not this file.
export const API_TAGS: { name: string; description: string }[] = [
  { name: "System", description: "Health probes for the gateway and each service." },
  { name: "Auth", description: "Sign-in, token refresh, and staff/rider account creation." },
  { name: "Auth - Registration", description: "Customer sign-up with the phone verified by OTP mid-form, before any account exists." },
  { name: "Auth - Login", description: "Customer sign-in by phone OTP or social provider. Email + password is under 'Auth'." },
  { name: "Auth - Password Reset", description: "Forgotten-password recovery by email OTP." },
  { name: "Auth - Account & Security", description: "Signed-in user: own profile, change password, optional extra verification (2FA), accept a staff invite, sign out." },
  { name: "Customer - Profile & Addresses", description: "CUSTOMER. Name and contact details, and saved pickup/delivery addresses (home, office)." },
  { name: "Customer - Ordering", description: "CUSTOMER. Choose what to wash, answer the quick care questions, check Express is honestly possible, pick a slot, place the order." },
  { name: "Customer - Orders & Tracking", description: "CUSTOMER. Order history, live tracking, cancel, reschedule, reorder." },
  { name: "Customer - Payments", description: "CUSTOMER. Pay for an order (Razorpay), saved payment methods, payment history." },
  { name: "Customer - Garment Care Profiles", description: "CUSTOMER. A reusable care profile per favourite garment, visible to every store it visits." },
  { name: "Customer - Offers & Loyalty", description: "CUSTOMER. Coupons, prepaid packages and loyalty points." },
  { name: "Customer - Feedback, Complaints & Support", description: "CUSTOMER. Rate an order, raise and follow a complaint against it, ask for support." },
  { name: "Customer - Notifications", description: "CUSTOMER. Choose SMS, email or WhatsApp updates, and read the inbox." },
  { name: "Rider - Onboarding", description: "PUBLIC. A prospective rider applies and uploads documents; no account exists yet." },
  { name: "Rider - Shift & Availability", description: "RIDER. Go available, share location, start and end a shift." },
  { name: "Rider - Jobs", description: "RIDER. The day's pickups and deliveries in route order, and reporting a problem at a door." },
  { name: "Rider - Pickup", description: "RIDER. Scan, inspect and photograph delicate items, get the customer's confirmation, hand off to the store." },
  { name: "Rider - Delivery & Payment", description: "RIDER. Deliver with a signature, and collect payment at the door if not paid online." },
  { name: "Rider - Earnings & Summary", description: "RIDER. The day's summary, earnings and customer ratings." },
  { name: "Store - Customers", description: "STORE. Look up and manage customers, including walk-ins." },
  { name: "Store - Orders", description: "STORE. Create, view, update and cancel orders, including counter (walk-in) orders." },
  { name: "Store - Check-in & Care", description: "STORE. Receive garments, see care flags at a glance, and decide the wash and dry process." },
  { name: "Store - Processing & Batches", description: "STORE. Group garments into batches and run them through the machines." },
  { name: "Store - Machines & Daily Checks", description: "STORE. Which machine is free, reserving one, the daily checks, and reporting a fault." },
  { name: "Store - Garment Tracking", description: "STORE. QR-tag scanning and garment images." },
  { name: "Store - Quality, Packing & Handover", description: "STORE. Final quality check, packing, marking ready, and counter collection." },
  { name: "Store - Invoices", description: "STORE. Invoice print data and monthly batch invoicing." },
  { name: "Store - Complaints", description: "STORE. Log a complaint against an order, assign it, resolve it, or escalate it." },
  { name: "Store - Cash & Banking", description: "STORE. Count the day's cash, record the bank deposit, close the day." },
  { name: "Store - Stock & Materials", description: "STORE. Stock levels and flagging materials that are running low." },
  { name: "Store - Day Operations", description: "STORE. Holidays, the daily report, today's tasks, resource readings and staff performance." },
  { name: "Dispatch - Jobs & Assignment", description: "STORE/ADMIN. Create pickup and delivery jobs, assign and reassign riders, see proof of delivery." },
  { name: "Dispatch - Riders & Cash", description: "STORE/ADMIN. Who is available and where, and the cash riders collect at the door." },
  { name: "Admin - Dashboard", description: "ADMIN. One view of revenue, orders, capacity, costs, cash, people, satisfaction and open risks." },
  { name: "Admin - Users", description: "ADMIN. Invite, list, change and deactivate accounts, and scope staff to stores." },
  { name: "Admin - Access Control", description: "ADMIN. Access policy rules." },
  { name: "Admin - Stores & Areas", description: "ADMIN. Stores, areas, and one place to see any store's performance." },
  { name: "Admin - Catalog & Pricing", description: "ADMIN. Services, garment types and fabric rules; one global price list with optional area and store overrides." },
  { name: "Admin - Capacity & Forecast", description: "ADMIN. Machines, staff and riders right now, the days ahead, and Express orders at risk." },
  { name: "Admin - Escalations & Feedback", description: "ADMIN. Final decision on escalated complaints, and customer feedback across stores and riders." },
  { name: "Admin - Coupons & Packages", description: "ADMIN. Coupons and prepaid packages." },
  { name: "Admin - Loyalty & Retention", description: "ADMIN. The loyalty programme, and customers who look like they are drifting away." },
  { name: "Admin - Campaigns & Notifications", description: "ADMIN. SMS, email and WhatsApp campaigns, message templates, and the delivery log." },
  { name: "Admin - Payments & Reconciliation", description: "ADMIN. Payments, mismatches, bank and gateway reconciliation, refunds." },
  { name: "Admin - Expenses & Operating Costs", description: "ADMIN. Expenses, and rent, utilities and every other recurring cost in one place." },
  { name: "Admin - GST, Receivables & Ledger", description: "ADMIN. Monthly GST reports, outstanding balances with automatic reminders, and the ledger." },
  { name: "Admin - Cash & Daily Close", description: "ADMIN. What was collected, what was banked, and whether the two agree, the same day." },
  { name: "Admin - Cost & Resource Analytics", description: "ADMIN. Water, electricity and detergent per order, and the real cost of running a store." },
  { name: "Admin - Security & Audit", description: "ADMIN. Who did what and when, across every store, and backup status." },
  { name: "HR - Employees & Onboarding", description: "HR. The employee directory, documents and induction for staff and riders alike." },
  { name: "HR - Training", description: "HR. Courses, what each role needs, assignments, and overdue or refresher training." },
  { name: "HR - Attendance", description: "HR. Who is in today, corrections, and the shift roster." },
  { name: "HR - Leave & Holidays", description: "HR. Approve or decline leave, balances and policies, and the holiday calendar." },
  { name: "HR - Absence Cover & Daily Reports", description: "HR. Cover for an unexpected absence, and the team's end-of-day reports." },
  { name: "HR - Performance & Appraisals", description: "HR. Performance over time, and scheduling, conducting and recording appraisals." },
  { name: "HR - Career Development", description: "HR. Career plans and agreed growth actions." },
  { name: "HR - Pay & Incentives", description: "HR. Pay details, incentive schemes and what each person has earned, approved and been paid." },
  { name: "HR - Grievances & Requests", description: "HR. Work confidential concerns to a recorded outcome, and answer HR requests." },
  { name: "HR - Rider Management", description: "HR. Review and verify rider applications, rider performance, and whether a rider may be given jobs." },
  { name: "Employee Self-Service - Attendance & Leave", description: "STAFF & RIDERS. Clock in and out, see own attendance, request leave." },
  { name: "Employee Self-Service - Reports & Training", description: "STAFF & RIDERS. Submit the end-of-day report, and do assigned training." },
  { name: "Employee Self-Service - Pay & Performance", description: "STAFF & RIDERS. Own pay, earnings, performance, reviews and career plan." },
  { name: "Employee Self-Service - Support & Safety", description: "STAFF & RIDERS. Raise a grievance or HR request, and see own incident reports." },
  { name: "Ops - Vendors & Purchasing", description: "HR. Suppliers, materials, what is running low, purchase orders and spend." },
  { name: "Ops - Equipment & Maintenance", description: "HR. Machine register, inspections, servicing due, repairs, downtime, replace-or-repair." },
  { name: "Ops - IT Assets & Requests", description: "HR. Laptops and devices, software licences, and IT requests from staff." },
  { name: "Ops - Insurance & Claims", description: "HR. Every policy, renewals before they lapse, and claims tracked to settlement." },
  { name: "Ops - Compliance", description: "HR. Licences, registrations and certificates, with reminders before they expire." },
  { name: "Ops - Audits", description: "HR. Plan audits, record findings, and keep them open until actually fixed." },
  { name: "Ops - Safety Incidents", description: "ANYONE reports; HR/ADMIN own it. Injuries, near misses, fire and security risks, escalated and closed out." },
];
