// @generated-scaffold — contract scaffold from the API catalogue; handlers answer 501 until built.
// Once you implement a handler, delete the first line so regeneration can never overwrite your work.
import express from "express";
import customerProfileRoutes from "./CustomerProfile.Routes.js";
import customerOrderingRoutes from "./CustomerOrdering.Routes.js";
import customerOrdersRoutes from "./CustomerOrders.Routes.js";
import customerPaymentsRoutes from "./CustomerPayments.Routes.js";
import customerGarmentProfilesRoutes from "./CustomerGarmentProfiles.Routes.js";
import customerSupportRoutes from "./CustomerSupport.Routes.js";
import storeOrdersRoutes from "./StoreOrders.Routes.js";
import storeCheckInRoutes from "./StoreCheckIn.Routes.js";
import storeProcessingRoutes from "./StoreProcessing.Routes.js";
import storeMachinesRoutes from "./StoreMachines.Routes.js";
import storeQualityRoutes from "./StoreQuality.Routes.js";
import storeComplaintsRoutes from "./StoreComplaints.Routes.js";
import storeCashRoutes from "./StoreCash.Routes.js";
import storeStockRoutes from "./StoreStock.Routes.js";
import storeDayOpsRoutes from "./StoreDayOps.Routes.js";
import adminStoresRoutes from "./AdminStores.Routes.js";
import adminPricingRoutes from "./AdminPricing.Routes.js";
import adminCapacityRoutes from "./AdminCapacity.Routes.js";
import adminFeedbackRoutes from "./AdminFeedback.Routes.js";
import hrEmployeesRoutes from "./HrEmployees.Routes.js";
import hrTrainingRoutes from "./HrTraining.Routes.js";
import hrAttendanceRoutes from "./HrAttendance.Routes.js";
import hrLeaveRoutes from "./HrLeave.Routes.js";
import hrCoverReportsRoutes from "./HrCoverReports.Routes.js";
import hrPerformanceRoutes from "./HrPerformance.Routes.js";
import hrCareerRoutes from "./HrCareer.Routes.js";
import hrPayRoutes from "./HrPay.Routes.js";
import hrGrievancesRoutes from "./HrGrievances.Routes.js";
import essAttendanceLeaveRoutes from "./EssAttendanceLeave.Routes.js";
import essReportsTrainingRoutes from "./EssReportsTraining.Routes.js";
import essPayPerformanceRoutes from "./EssPayPerformance.Routes.js";
import essSupportSafetyRoutes from "./EssSupportSafety.Routes.js";
import opsVendorsRoutes from "./OpsVendors.Routes.js";
import opsEquipmentRoutes from "./OpsEquipment.Routes.js";
import opsItRoutes from "./OpsIt.Routes.js";
import opsInsuranceRoutes from "./OpsInsurance.Routes.js";
import opsComplianceRoutes from "./OpsCompliance.Routes.js";
import opsAuditsRoutes from "./OpsAudits.Routes.js";
import opsIncidentsRoutes from "./OpsIncidents.Routes.js";

const router = express.Router();

router.use(customerProfileRoutes);
router.use(customerOrderingRoutes);
router.use(customerOrdersRoutes);
router.use(customerPaymentsRoutes);
router.use(customerGarmentProfilesRoutes);
router.use(customerSupportRoutes);
router.use(storeOrdersRoutes);
router.use(storeCheckInRoutes);
router.use(storeProcessingRoutes);
router.use(storeMachinesRoutes);
router.use(storeQualityRoutes);
router.use(storeComplaintsRoutes);
router.use(storeCashRoutes);
router.use(storeStockRoutes);
router.use(storeDayOpsRoutes);
router.use(adminStoresRoutes);
router.use(adminPricingRoutes);
router.use(adminCapacityRoutes);
router.use(adminFeedbackRoutes);
router.use(hrEmployeesRoutes);
router.use(hrTrainingRoutes);
router.use(hrAttendanceRoutes);
router.use(hrLeaveRoutes);
router.use(hrCoverReportsRoutes);
router.use(hrPerformanceRoutes);
router.use(hrCareerRoutes);
router.use(hrPayRoutes);
router.use(hrGrievancesRoutes);
router.use(essAttendanceLeaveRoutes);
router.use(essReportsTrainingRoutes);
router.use(essPayPerformanceRoutes);
router.use(essSupportSafetyRoutes);
router.use(opsVendorsRoutes);
router.use(opsEquipmentRoutes);
router.use(opsItRoutes);
router.use(opsInsuranceRoutes);
router.use(opsComplianceRoutes);
router.use(opsAuditsRoutes);
router.use(opsIncidentsRoutes);

export default router;
